/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashSet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void rollTest (){

        int[] rollAns5=App.roll(5);
        assertEquals(5,rollAns5.length);

        int[] rollAns0=App.roll(0);
        assertEquals(0,rollAns0.length);
    }

    @Test
    void containsDuplicatesTest (){
        int[] arr1 = {1,2,3,4,5,6};
        boolean test1=App.containsDuplicates(arr1);
        assertFalse(test1);

        int[] arr2 = {1,2,3,4,5,6,1};
        boolean test2=App.containsDuplicates(arr2);
        assertTrue(test2);
    }

    @Test
    void calculatingAveragesTest (){
        int[] arr1 = {5,5,5,5,5,5};
        double test1=App.calculatingAverages(arr1);
        assertEquals(5,test1);

        int[] arr2 = {1,2,3,4,5,6};
        double test2=App.calculatingAverages(arr2);
        assertEquals(3.5,test2);
    }
    @Test
    void arraysOfArraysTest (){
        int[][] arr1 = {
                {1, 1, 1, 1, 1, 1, 1},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] ansArr={1, 1, 1, 1, 1, 1, 1};
        int[] test1=App.arraysOfArrays(arr1);
        assertArrayEquals(ansArr,test1);

    }
    @Test
    void tallyTest (){
        ArrayList<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String answer="Bush";
        String test1=App.tally(votes);


        assertEquals(answer,test1);
    }

    @Test
    void analyzingWeatherDataTest (){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        HashSet<String> ansArr= new HashSet<>();
        ansArr.add("Never saw temperature: 63");
        ansArr.add("Never saw temperature: 67");
        ansArr.add("Never saw temperature: 68");
        ansArr.add("Never saw temperature: 69");


        HashSet<String> test1=App.analyzingWeatherData(weeklyMonthTemperatures);
        assertEquals(ansArr,test1);

    }


}
