/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    Restaurant restaurant = new Restaurant("restaurantTest" , "$$$" );
    Review review = new Review("very good meals","Bara'ah",5);


    @Test void testToStringRestaurant() { //Test that your Restaurant constructor is behaving reasonably.
        String ans =restaurant.toString();
        String expectedAns = "Restaurant{name='restaurantTest', stars=0.0, priceCategory='$$$', reviews=[]}";
        assertEquals(expectedAns,ans);

    }

    @Test void testToStringReview() {  //Test that your constructor is working reasonably.
        String ans =review.toString();
        String expectedAns = "Review{body='very good meals', author='Bara'ah', reviewStars=5.0}";
        assertEquals(expectedAns,ans);
    }
    @Test void testAddingOutOfBoundsStars() {  //Test that your constructor is working reasonably.
        Review badReview = new Review("very bad","Hala",-10);
        Review goodReview = new Review("THE BEST EVER", "Mona",100);


        String ans =review.toString();
        String expectedAns = "Review{body='very good meals', author='Bara'ah', reviewStars=5.0}";
        assertEquals(expectedAns,ans);
    }


    @Test void addReviewTest () {
        restaurant.addReview("very good meals","Bara'ah",5);
        restaurant.addReview("very good looking","Hala",2);
        String ans =restaurant.toString();
        String expectedAns = "Restaurant{name='restaurantTest', stars=3.5, priceCategory='$$$', reviews=[Review{body='very good meals', author='Bara'ah', reviewStars=5.0}, Review{body='very good looking', author='Hala', reviewStars=2.0}]}";
        assertEquals(expectedAns,ans);

    }

}
