/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class App {
    public int[] roll(int n) {
        int[] ansArr=new int[n+1];


        return ansArr;
    }

    public static void main(String[] args) {
        System.out.println();
    }
}
